SELECT * FROM USER_TABLES;
SELECT * FROM USER_SEQUENCES;
SELECT TABLE_NAME FROM USER_TABLES;
SELECT SEQUENCE_NAME FROM USER_SEQUENCES;


SELECT * FROM MEMBER

INSERT INTO AIRECOMMEND VALUES(AIRECOMMEND_SEQ.NEXTVAL, 'admin', 20, NULL, NULL, SYSDATE)

SELECT * FROM AIRECOMMEND


SELECT * FROM BLACKLIST
SELECT BLACKLIST_NO, BLACKLIST_FROM, BLACKLIST_TO, BLACKLIST_CONTENTS, BLACKLIST_DATE FROM BLACKLIST

INSERT INTO BLACKLIST VALUES(BLACKLIST_SEQ.NEXTVAL, 'admin', 'admin', '신고하기 실험중', SYSDATE)



