CREATE SEQUENCE MEMBERSEQ;
DROP SEQUENCE MEMBERSEQ;

INSERT INTO MEMBER VALUES(MEMBERSEQ.NEXTVAL, 'admin', 'admin1234', 20, 'F', 'admin@admin.com', 'Y', 'Y', 'ADMIN', 'GENERAL', 'N');
INSERT INTO MEMBER VALUES(MEMBERSEQ.NEXTVAL, 'admin2', 'admin1234', 20, 'F', 'admin@admin.com', 'Y', 'Y', 'ADMIN', 'GENERAL', 'N');

SELECT * FROM MEMBER



DELETE FROM MEMBER
WHERE MEMBER_ID='1234'







INSERT INTO PAYTABLE
VALUES (PAY_NO.NEXTVAL,'5000','회원권',SYSDATE,'admin')

SELECT * FROM PAYTABLE

SELECT MEMBER_PAYROLE
FROM MEMBER
WHERE MEMBER_ID='woobin'

DELETE FROM PAYTABLE
WHERE PAY_ID = 'admin'

UPDATE MEMBER SET MEMBER_PAYROLE = 'N'
WHERE MEMBER_ID ='1234'










CREATE SEQUENCE INTD_NO

INSERT INTO INTRODUCETABLE
VALUES('woobin123','안녕하세요',INTD_NO.NEXTVAL)

SELECT * FROM INTRODUCETABLE;

SELECT INTD_NO,INTD_ID,INTD_CONTENT
FROM INTRODUCETABLE
WHERE INTD_ID= 'user' ;

SELECT INTD_ID,INTD_CONTENT
FROM MEMBER INNER JOIN INTRODUCETABLE
ON MEMBER.MEMBER_ID = INTRODUCETABLE.INTD_ID
WHERE MEMBER_ID  ='user';

DELETE FROM INTRODUCETABLE
WHERE INTD_ID ='woobin123'




SELECT *FROM BOOK
INSERT INTO BOOK
VALUES(456789123,'TESTBOOK3','test3','test3','test3',SYSDATE,3000,'TEST3','TEST3',7.5,'Y')




CREATE SEQUENCE SCRAP_NO

SELECT SCRAP_NO,SCRAP_ID,BOOK_ISBN,SCRAP_REGDATE,BOOK_TITLE
FROM SCRAP
WHERE SCRAP_ID ='woobin123'
ORDER BY SCRAP_NO DESC

SELECT * FROM SCRAP

INSERT INTO SCRAP
VALUES(SCRAP_NO.NEXTVAL,'woobin',456789123,SYSDATE,'방탄')

DELETE FROM SCRAP
WHERE SCRAP_ID='woobin'

SELECT SCRAP_NO,BOOK_ISBN,SCRAP_REGDATE,BOOK_TITLE
FROM MEMBER INNER JOIN SCRAP
ON MEMBER.MEMBER_ID = SCRAP.SCRAP_ID

WHERE MEMBER_ID = 'woobin'


		


CREATE SEQUENCE RCVIDEO_NO

SELECT * FROM RCVIDEOTABLE;

INSERT INTO RCVIDEOTABLE
VALUES(RCVIDEO_NO.NEXTVAL,'소개합니당','9788960536036')

DELETE FROM RCVIDEOTABLE

SELECT RCVIDEO_NO,RCVIDEO_CONTENT,RCVIDEOTABLE.BOOK_ISBN AS BOOK_ISBN,SCRAP.BOOK_ISBN AS BOOK_ISBN
FROM SCRAP INNER JOIN RCVIDEOTABLE
ON SCRAP.BOOK_ISBN = RCVIDEOTABLE.BOOK_ISBN
WHERE SCRAP.BOOK_ISBN = RCVIDEOTABLE.BOOK_ISBN

SELECT RCVIDEOTABLE.RCVIDEO_NO,RCVIDEOTABLE.RCVIDEO_CONTENT,RCVIDEOTABLE.BOOK_ISBN AS bOOK_ISBN,SCRAP.BOOK_ISBN AS BOOK_iSBN
FROM RCVIDEOTABLE,SCRAP
WHERE SCRAP.BOOK_ISBN ='9788960536036'









